### ISSUE TITLE
Docs generation problem

### ISSUE THREAD

**Issue by qshiyou** [ThoughtWorksInc/treadmill#74]
To generate docs automaticall by running:
    python docs/cli_doc_generator.py

An error occurred as follow:

Traceback (most recent call last):
  File "/home/centos/env/lib/python3.4/site-packages/kazoo-2.2.1-py3.4.egg/kazoo/recipe/watchers.py", line 333, in _get_children
    result = self._func(children)
  File "/home/centos/env/lib/python3.4/site-packages/Treadmill-3.0_2017.04.29_1.post103_0fcf6ed-py3.4.egg/treadmill/api/state.py", line 182, in _watch_tasks_history
    f.write(zlib.decompress(data))
zlib.error: Error -3 while decompressing data: incorrect header check

Thanks!

**Comment by snyaggarwal** [comment]
This has been resolved, can you please take latest.

**Comment by qshiyou** [comment]
Thank you very much! We'll try the latest version.
